export const data = [

  {
    key: '00',
    href: '/',
    title: 'Alex',
    avatar: '/',
    description: 'Lanikai Pillbox',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 4,
    content: 'Simple hike, great view!',
    src: 'https://wpcdn.us-east-1.vip.tn-cloud.net/www.hawaiimagazine.com/content/uploads/2020/12/Oahu_Pillbox_MikeKaras_web1285horizontal.jpg',
    alt: 'Hikers sitting on a pillbox on the edge of a cliff with view of blue ocean and houses below'
  },
  {
    key: '01',
    href: '/',
    title: 'Joe',
    avatar: '/',
    description: 'Manoa Falls',
    duration: '2hr',
    difficulty: 'Moderate',
    rating: 4,
    content: 'Challenging but worth it for the waterfall!',
    src: 'https://a.cdn-hotels.com/gdcs/production77/d1134/afbd6f7d-37e6-4630-be62-462e7fbc34df.jpg',
    alt: 'Waterfall pouring into pond against a mossy rock wall'
  },
  {
    key: '02',
    href: '/',
    title: 'Ava',
    avatar: '/',
    description: 'Ka\'au Crater',
    duration: '3hr',
    difficulty: 'Hard',
    rating: 5,
    content: 'Challenging trail with three waterfalls. Amazing!',
    src: 'https://th.bing.com/th/id/OIP.ETaZ-5ge0xCgkcP9jKNB9wHaES?rs=1&pid=ImgDetMain',
    alt: 'Aerial view of crater valley ridges overgrown with greenery'
  },
  {
    key: '03',
    href: '/',
    title: 'John',
    avatar: '/',
    description: 'Diamond Head Crater',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 4,
    content: 'A bit crowded, but the view is unbeatable!',
    src: 'https://i2.wp.com/thepointsguy.com/wp-content/uploads/2020/06/Diamond-Head-Crater.jpg?fit=2048%2C2048px&ssl=1',
    alt: 'Aerial view of crater with ocean surrounding and town in the background'
  },
  {
    key: '04',
    href: '/',
    title: 'Emma',
    avatar: '/',
    description: 'Koko Head Stairs',
    duration: '1hr',
    difficulty: 'Hard',
    rating: 3,
    content: 'Tough climb, but the panoramic views are worth it!',
    src: 'https://www.journeyera.com/wp-content/uploads/2016/05/DSC02440-scaled.jpg',
    alt: 'View of wooden steps with hikers going downwards with city and ocean in the background'
  },
  {
    key: '05',
    href: '/',
    title: 'Oliver',
    avatar: '/',
    description: 'Makapu\'u Lighthouse Trail',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 5,
    content: 'Easy walk, stunning ocean views!',
    src: 'https://loveoahu.org/wp-content/uploads/Makapuu-Lighthouse-HTA-tor-johnson.jpg',
    alt: 'Rocky cliffside with red and white lighthouse overlooking the ocean with small islands'
  },
  {
    key: '06',
    href: '/',
    title: 'Lucas',
    avatar: '/',
    description: 'Wiliwilinui Ridge Trail',
    duration: '2hr',
    difficulty: 'Moderate',
    rating: 4,
    content: 'Great workout and beautiful ridge views!',
    src: 'https://th.bing.com/th/id/R.b39c5c29b179bdf8d13c2352a3f10809?rik=la2%2bdDqpDrDe4A&riu=http%3a%2f%2fstatic1.squarespace.com%2fstatic%2f5a9df9f4a9e028af26f1eb8c%2f5aa0b9a08165f5eecd2f0f63%2f6181ca21a2f2e51ecd4c0042%2f1664024485561%2fwiliwilinui-ridge-trail-hikes-in-oahu-ridge-trail-uprooted-traveler.jpg%3fformat%3d1500w&ehk=mAZ6tUvia1GxUADBwaz8yfaib%2bwTMmDZ6Png0v8K1hw%3d&risl=&pid=ImgRaw&r=0',
    alt: 'Hiker descending trail overlooking green mountain ridges at sunset'
  },
  {
    key: '07',
    href: '/',
    title: 'Mia',
    avatar: '/',
    description: 'Ehukai Pillbox Hike',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 4,
    content: 'Short hike with a rewarding view of the North Shore!',
    src: 'https://uprootedtraveler.com/wp-content/uploads/ehukai-pillbox-hike-hikes-in-oahu-sunse-north-shore-hikes.jpeg',
    alt: 'Hiker standing on the pillbox looking out towards view of ocean and houses below'
  },
  {
    key: '08',
    href: '/',
    title: 'Liam',
    avatar: '/',
    description: 'Aiea Loop Trail',
    duration: '2hr',
    difficulty: 'Moderate',
    rating: 3,
    content: 'Nice forest trail with views of Pearl Harbor.',
    src: 'https://wpcdn.us-east-1.vip.tn-cloud.net/www.hawaiimagazine.com/content/uploads/2020/12/aiealoop.jpg',
    alt: 'View of highway curving around green mountain ranges with trees'
  },
  {
    key: '09',
    href: '/',
    title: 'Isabella',
    avatar: '/',
    description: 'Kuliouou Ridge Trail',
    duration: '2hr',
    difficulty: 'Moderate',
    rating: 4,
    content: 'Steep but not too long. The view at the top is breathtaking!',
    src: 'https://th.bing.com/th/id/OIP.18z14G7os60KfrNRtoSAQwAAAA?rs=1&pid=ImgDetMain',
    alt: 'Two hikers sitting on the edge of a cliff with view of green sloped mountain range'
  },
  {
    key: '10',
    href: '/',
    title: 'Ethan',
    avatar: '/',
    description: 'Maunawili Falls Trail',
    duration: '2hr',
    difficulty: 'Moderate',
    rating: 4,
    content: 'Muddy but fun, with a great waterfall at the end!',
    src: 'https://drscdn.500px.org/photo/41126720/q%3D80_m%3D1500/v2?sig=1656904f15a749732c1f5b8170929c8c8af67f0cb220dc13bb0dd45680234d3d',
    alt: 'Small waterfall pouring into a green pond with rocky sloped wall covered in moss behind it'
  },
  {
    key: '11',
    href: '/',
    title: 'Sophia',
    avatar: '/',
    description: 'Olomana Three Peaks',
    duration: '3hr',
    difficulty: 'Hard',
    rating: 5,
    content: 'Very challenging but the views are spectacular!',
    src: 'https://1lifeonearth.com/wp-content/uploads/2017/04/DSC_7533-2000-7-.jpg',
    alt: 'Hiker standing on the ridge with a view of green mountain ridge ahead peaking tall'
  },
  {
    key: '12',
    href: '/',
    title: 'Mason',
    avatar: '/',
    description: 'Lanipo Trail',
    duration: '3hr',
    difficulty: 'Hard',
    rating: 4,
    content: 'Long and tough, but the panoramic views are worth it!',
    src: 'https://d34ky9neaf8crv.cloudfront.net/pix/0nrrnib83ahvyx5jlg9v.2.jpg',
    alt: 'Mountain ridge with green shrubbery and a couple cell towers'
  },
  {
    key: '13',
    href: '/',
    title: 'Charlotte',
    avatar: '/',
    description: 'Waimea Valley',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 5,
    content: 'Easy walk with a beautiful waterfall. Great for kids!',
    src: 'https://ik.imgkit.net/3vlqs5axxjf/TW/uploadedImages/Art/2021/1101/T1101WAIMEAVALLEYFALLS_TL_HR_ALT.jpg?tr=w-1540%2Ch-866%2Cfo-auto',
    alt: 'Waterfall pouring into large blue pong with hikers swimming and rocky wall with trees and greenery'
  },
  {
    key: '14',
    href: '/',
    title: 'James',
    avatar: '/',
    description: 'Kaneohe Pillbox',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 4,
    content: 'Short hike with a rewarding view of the Windward side!',
    src: 'https://1.bp.blogspot.com/-qKduejDYggc/VV_tRHjUEaI/AAAAAAAAAYc/aRdAZE3-65g/s1600/IMG_2610.JPG',
    alt: 'Overlooking blue sandy bay with mountain ranges in the back and houses below'
  },
  {
    key: '15',
    href: '/',
    title: 'Amelia',
    avatar: '/',
    description: 'Pali Puka Lookout',
    duration: '1hr',
    difficulty: 'Moderate',
    rating: 4,
    content: 'Short but steep. The view of the Windward side is amazing!',
    src: 'https://www.journeyera.com/wp-content/uploads/2016/10/pali-puka--1024x683.jpg',
    alt: 'Rocky formation with hole in the middle showing a view of green trees and houses below'
  },
  {
    key: '16',
    href: '/',
    title: 'Benjamin',
    avatar: '/',
    description: 'Hanauma Bay Ridge',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 4,
    content: 'Great views of Hanauma Bay and Koko Head!',
    src: 'https://www.hawaiiactivities.com/travelguide/wp-content/uploads/Hanauma-Bay-Header.jpg',
    alt: 'View from atop the hillside of blue water with coral and mountains wrapping around each side'
  },
  {
    key: '17',
    href: '/',
    title: 'Harper',
    avatar: '/',
    description: 'Kealia Trail',
    duration: '2hr',
    difficulty: 'Moderate',
    rating: 4,
    content: 'Easier than expected. Beautiful ocean views!',
    src: 'https://www.homeyhawaii.com/blog/wp-content/uploads/2019/06/kealia-trail-view.jpg',
    alt: 'Green rocky mountain side with a bright blue ocean background.'
  },
  {
    key: '18',
    href: '/',
    title: 'Elijah',
    avatar: '/',
    description: 'Kapena Falls',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 4,
    content: 'Short hike to a hidden waterfall. A hidden gem!',
    src: 'https://www.outdoorproject.com/sites/default/files/styles/hero_image_desktop/public/1532929529/dsc01947.jpg?itok=fJb0dCO5',
    alt: 'Small waterfall pouring into large green pond with large rock cliffs and overarching trees.'
  },
  {
    key: '19',
    href: '/',
    title: 'Luna',
    avatar: '/',
    description: 'Judd Trail',
    duration: '1hr',
    difficulty: 'Easy',
    rating: 3,
    content: 'Easy hike through the forest. Great for a family day out!',
    src: 'https://wpcdn.us-midwest-1.vip.tn-cloud.net/www.honolulumagazine.com/content/uploads/data-import/7ad3c565/hike-of-the-month-judd-trail-jackass-ginger-pool.jpg',
    alt: 'Overhead view of small waterfall with hikers jumping into dark green pond surrounded by greenery and palm trees.'
  }
];

export const lang = 'en_US'; // en_US From Antd fr_CA is French Canadian

export const strings = {

  en_US: {
    disc: 'Discover',
    feed: 'Feed',
    share: 'Share',
    about: 'About Us',
    title1: 'Discover, Experience, Share',
    title2: 'Explore trails recommended by our experts',
    text1: 'Find a hike today',
    text2: 'Explore Popular routes',
    text3: 'Post reviews and talk about your experience on the hike!',
    contact: 'Contact Us',
    search: 'Search',
    submit: 'Submit',
    shr_str: 'Star Rating',
    shr_dif: 'Difficulty',
    shr_dur: 'Duration',
    shr_fil: 'Upload Images',
  },

  fr_CA: {
    disc: 'Decouvrez',
    feed: 'Flux',
    share: 'Partager',
    about: 'A Propos',
    title1: 'Decouvrez, Experiences, Partagez',
    title2: 'Explorer les parcours recommandes par nos experts',
    text1: "Trouvez un parcours aujourd'hui",
    text2: 'Exlplorez les routes Populaires',
    text3: 'Partagez vos experiences!',
    contact: 'Contactez Nous',
    search: 'Cherchez',
    submit: 'Soumettre',
    shr_str: 'Etoiles',
    shr_dif: 'Difficulté',
    shr_dur: 'Durée',
    shr_fil: 'Importer des images',
  },
}